language: node_js
node_js:
  - "lts/*"
before_script:
  - npm install -g tfx-cli
script:
  - tfx extension create --manifest-globs vss-extension.json
deploy:
  provider: releases
  api_key:
    secure: "eEgzg1dGH8IfT/sW8ej7SwhcslSCs+MGFsXa7FaEdg4ZQ3L+R1ufwbAgAIyiucIIREa5oBiOwDSXjWxtoEqwX4+CYLN+R6/teWdYQA92x79aU60Qk6dS9IbptZRKrnnKN/PSdxWcftSHguTx9M88Qnpuh4GpzJKGuO3JjWxQ2Ygv+YvlQHFihyVaMGaNiHJa2br/0M3IX9GYEeIyXkJcnPQKjc0j3m39/Ks/MUBzg1y7ddgaB336PvftOw8tgyTS+wLR1X0i+xoGyxNZo+9Ew+dCpMFbuHYfO883HZgQxCNT29U5nXrpiMTUJwoa4lB3w+fR+2GKhobODCNsPWXvSWPRm3yDkHLPI9VmzNB1FgKSJ+0j8TToWiBraCNVTtdAlDnVM/4bHA+xg5fO1Sx0lUz/RZDz2K6PQywiDuLG9eGaOhbccn4BvMj2FC26PftB/oDpuSFzFvwmuSWFWz/EugzKnJTyMq5S+CgH8N6C6+ZtO4bTCtmgHzyAnovBjOl74Nq58Xl+t5sWgKRLMbz+evnIiLcbpxa9G5UibHzFc1GTJ1Gs50fG4V0Q+On0t8YNfRI+rcNtYvEGQ+jA057m4yH3HWbJPf24gbbndEgTvO+51jBJLI6Vu3p2NgHLbA3alnGqLSl8GgrCJ/ObpxLKQ3Ce+MljloZmSGS5Wu0/Uuo="
  file: yunfan.nsis-task-*.vsix
  file_glob: true
  skip_cleanup: true
  on:
    tags: true