language: node_js
node_js:
  - "lts/*"
before_script:
  - npm install -g tfx-cli
script:
  - tfx extension create --manifest-globs vss-extension.json
deploy:
  provider: releases
  api_key:
    secure: "mXTI+FCis1rUvb76wuRDnW0ZA4ZbtkadjqiOhpHLQTwxxsdztHDohV2Yz60VFswrFzDS3g9DjkGbXe0SW3c6Ks3MSe0Rdd55Dq9jtjPFuaFOh9TPK9ibv2zqEbzd28sErEfMmsxE/C0MqsKgq9ys1LRuXKGqanCcrjZYsOaeLGHPIBmgMzWZ32lpMkhap+TFuSH24TBZptd95AaanT7fHrua0i8hV17CoA5FrJWjYf1ElVmlJZC5FNiGBCNMvFz98vSSIka75YkGkMOsuGSFfyg3JlAJJEt5TAwWI+x16RbS2XQZtvkZKlq+TvSInzJ5KBl7j3/QqR7djMs39UnfpPfVNRV+NWM197ADOoZkHsDvmyP6lNK55OfpCHpyhv1tE2F4ui3DNTXwoREDM7kgjE6Ir/Z0zjXJSHDuWMzlDYeOST8Zajq24o7R0YcZUCgsHNfPh6V13lfXoYvvlDR32uVb0WOdi/cd2bRG+r1mHEZ9rDbvEvyME+sFCf3QXnAAf5u+z4DBaydmQKqc9O08m4fZfyQT6eEGNaXdSFRjM6TwyQOQOKtFJjpXHFOXt56yK35QuY/+f48HpD3CyNwaFy/yvGQLFC6HLpej9W1S3o5iVYfhkD/3muvjkUmXqIWDOsbXEU39V7tCqVv0CXv3AQHx+Jghy5419UWUx0ZM+xM="
  file: yunfan.nsis-task-*.vsix
  file_glob: true
  skip_cleanup: true
  on:
    tags: true